defaults:
  - agent: ddpgbc
  - _self_

# File path
cwd: ${hydra:runtime.output_dir}

# Training params
n_train_steps: 100_001
n_eval: 10
n_save: 5
n_log: 100
num_demo: 100
n_seed_steps: ${agent.n_seed_steps}

replay_buffer_capacity: 100_000
batch_size: 128
device: cuda:0
seed: 1
task: NeedlePick-v0
postfix: null
dont_save: False
n_eval_episodes: 20
demo_path: /home/jwfu/SurRoL/surrol/data/demo/data_NeedlePick-v0_random_100.npz

use_wb: False
project_name: surrol
entity_name: fujiawei0724

# MPI
mpi: {rank: null, is_chef: null, num_workers: null}

# Working space
hydra:
  run:
    dir: ./exp_local/${task}/${agent.name}/d${num_demo}/s${seed}
  sweep:
    dir: ./exp_local/${task}/${agent.name}/d${num_demo}
    subdir: ${seed}
  sweeper:
    params:
      seed: 1,2,3,4,5
